### ISSUE TITLE
Feature: Allow staying offline while syncing

### ISSUE THREAD

**Issue by krombel** [turt2live/matrix-js-bot-sdk#1]
I want to do run syncing with the param `set_presence=offline` as specced [here](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#get-matrix-client-r0-sync)

UseCase: Run the bot as silent client as myself while people still see if I am online or not

**Comment by turt2live** [comment]
That parameter actually allows other values as well, it's just not specced. Still a good feature to have though :)
