### ISSUE TITLE
Expose appservice express app for extra endpoints

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#10]
The `matrix-appservice-bridge` library adds additional endpoints specific to itself, so it would be nice to add our own routes to it.

**Comment by turt2live** [comment]
I'm kinda hesitant to do this for many reasons, but wouldn't oppose to having get/put/post/etc exposed.

**Comment by Half-Shot** [comment]
I'd be fine with "addEndpoint(method: "get"|"post"|"put", endpoint: string", handler: (req, res) => void)". I realise it's a pain, but it's that or I have to setup my own express, or ask you to merge stuff like my room link validator.

**Comment by turt2live** [comment]
yup, I just don't want to have the sdk depend on express being the http server, even though it's seriously unlikely to ever change.

**Comment by Half-Shot** [comment]
Works for me :)
