### ISSUE TITLE
Consider shorthanding appservice.botIntent.underlyingClient to appservice.botClient

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#27]
The client holds a vast number of useful things that we are using in the bridge, but it's a little ugly to have to access the client indirectly. I realise it might slightly uglyify the shape of your API, but would be useful nontheless.

**Comment by turt2live** [comment]
Concern is more that people would be bypassing `ensureRegistered` and less API shape (I don't mind throwing around MatrixClient objects). Nothing documentation can't solve though.
