### ISSUE TITLE
Template repos for bots and appservices

### ISSUE THREAD

**Issue by turt2live** [turt2live/matrix-js-bot-sdk#32]
https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/

**Comment by Cadair** [comment]
and / or https://github.com/audreyr/cookiecutter :smile:

**Comment by turt2live** [comment]
This is also heavily tied in with https://github.com/turt2live/matrix-js-bot-sdk/issues/22

**Comment by turt2live** [comment]
Bot repo: https://github.com/turt2live/matrix-bot-sdk-bot-template
