### ISSUE TITLE
Appservice Intent ensureJoined

### ISSUE THREAD

**Issue by Sorunome** [turt2live/matrix-js-bot-sdk#40]
Currently Appservice `Intent.ensureJoined()` returns `undefined` if the ghost was already in the room, elsewise it returns the rooms mxid

This is really helpful to detect if a join actually happened, for if you needed to do some additional stuff based on that.

Perhaps consider this a feature, document it and set the return type that function correctly to `Promise<string | undefined>`

**Comment by turt2live** [comment]
Closing in favour of https://github.com/turt2live/matrix-js-bot-sdk/issues/41

As per the chat - it's expected to be fire&forget, per the docs on the function.
