### ISSUE TITLE
Publish docs on the API

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#52]
I'm surprised this isn't an issue (perhaps we all rely on intellisense :p).

**Comment by Half-Shot** [comment]
@turt2live This still needs some kind of hosting for docs for the last release (and all subsequent ones)

**Comment by turt2live** [comment]
I'm not going to bother with the previous releases tbh. Starting with 0.4.0 is fine

**Comment by turt2live** [comment]
https://turt2live.github.io/matrix-js-bot-sdk/index.html is now a thing. It only serves develop right now because of limitations in the github actions workflow, but whatever. I'll probably build some other CI script to actually collate the releases and publish them myself, eventually.
