### ISSUE TITLE
@types/express should be a devDependency

### ISSUE THREAD

**Issue by Half-Shot** [turt2live/matrix-js-bot-sdk#64]
https://github.com/turt2live/matrix-js-bot-sdk/blob/fd950f606e76867d2bf3e8e10913755269ebea4d/package.json#L50

**Comment by turt2live** [comment]
If it is, it doesn't build.

**Comment by Half-Shot** [comment]
That smells like a bug to me.

**Comment by turt2live** [comment]
It's how TypeScript works - the types need to be brought into the project that uses the SDK otherwise it can't build the SDK into the project's output.

**Comment by Half-Shot** [comment]
Why are you trying to build the SDK in the project?

**Comment by turt2live** [comment]
You aren't, typescript is. It takes the mappings from the bot-sdk and tries to hunt down the express mappings. Honestly this would all be fixed with #62 rather than trying to shove this specific dependency out of the way.
