### ISSUE TITLE
[Appservice][Feature Request] Allow onRoomAlias to completly handle room creation or aliasing.

### ISSUE THREAD

**Issue by Kanaye** [turt2live/matrix-js-bot-sdk#66]
Hi!
I have an usecase where a new room alias can lead to an already existing room.
Unfortunatly I can not query possible room aliases and set them up before the homeserver queries the room.
So at least for my usecase it would be benifitial if I could skip the part where the appservice creates a room and just add an alias to the existing room.

My proposal would add a shortcut to the callback handling `true` (same as the sdk already handles `false` and sends a 404).
So an example would look like that:
```ts
appservice.on("query.room", async (alias, fn) => {
    /* some userspace code handling setup of the required alias */
    fn(true);
});
```

This would be fairly easy to implement as it's basicly just adding:
```ts
else if (result === true) {
   res.status(200).json({});
}
```
here: https://github.com/turt2live/matrix-js-bot-sdk/blob/fd950f606e76867d2bf3e8e10913755269ebea4d/src/appservice/Appservice.ts#L655

What Do you think and thanks for your time.

**Comment by turt2live** [comment]
I think this might need spec support because the endpoint is only supposed to return 200 if the room was created, not that it exists.
