### ISSUE TITLE
Huge wall of errors

### ISSUE THREAD

**Issue by Sorunome** [turt2live/matrix-js-bot-sdk#76]
Every time a ghost joins soru gets a huge error message dump because of https://github.com/turt2live/matrix-js-bot-sdk/blob/master/src/strategies/AppserviceJoinRoomStrategy.ts#L21

This seems kind of silly as
1. the log level is at "error", even though that is something expected to happen, which is why the strategy exists
2. instead of logging `err` logging something like `err.error || err.body || err` greatly reduces the unneeded clutter of the error, reducing it to what is actually relevant

**Comment by turt2live** [comment]
That's actually just some old debugging code left behind... oops.

**Comment by turt2live** [comment]
Fixed in https://github.com/turt2live/matrix-js-bot-sdk/commit/864657da5f1d52dcee5a7b53ebe9051341c22d25
